name: Typescript CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node LTS v18.4.0
      uses: actions/setup-node@v1
      with:
        node-version: 18.4.0
    - name: npm install
      run: npm install
    - name: build
      uses: iCrawl/action-tsc@v1
      run: npm run build
